defmodule Quorum.Repo.Migrations.AddQuestionsAndModeration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      add :question_max_length, :bigint, null: false, default: 500
      add :questions_per_student, :bigint, null: false, default: 0
      add :allow_display_name?, :boolean, null: false, default: true
      add :hold_for_review?, :boolean, null: false, default: false
      add :held_words, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:rooms) do
      remove :held_words
      remove :hold_for_review?
      remove :allow_display_name?
      remove :questions_per_student
      remove :question_max_length
    end
  end
end
