defmodule Quorum.Repo.Migrations.AddProjectionDisplay do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      add :projection_question_scale, :bigint, null: false, default: 100
      add :projection_show_asker?, :boolean, null: false, default: true
      add :projection_show_votes?, :boolean, null: false, default: true
      add :projection_show_joining?, :boolean, null: false, default: true
      add :projection_show_counts?, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:rooms) do
      remove :projection_show_counts?
      remove :projection_show_joining?
      remove :projection_show_votes?
      remove :projection_show_asker?
      remove :projection_question_scale
    end
  end
end
