defmodule Quorum.Repo.Migrations.AddRetentionAndVoteCascade do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      add :keep_questions?, :boolean, null: false, default: true
    end

    drop constraint(:votes, "votes_question_id_fkey")

    alter table(:votes) do
      modify :question_id,
             references(:questions,
               column: :id,
               name: "votes_question_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:votes, "votes_question_id_fkey")

    alter table(:votes) do
      modify :question_id,
             references(:questions,
               column: :id,
               name: "votes_question_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:rooms) do
      remove :keep_questions?
    end
  end
end
