defmodule Quorum.Repo.Migrations.AddSpotlight do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      add :spotlight_question_id,
          references(:questions,
            column: :id,
            name: "rooms_spotlight_question_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:rooms, "rooms_spotlight_question_id_fkey")

    alter table(:rooms) do
      remove :spotlight_question_id
    end
  end
end
