defmodule Quorum.Repo.Migrations.DefaultRoomInjectionScreen do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      modify :hold_injection?, :boolean, default: true
    end

    # Rooms made before the default changed still carry false. The demo room is
    # kept open rather than reseeded, so without this the live demo would never
    # pick the new default up. One operator's rooms, so turning the screen on
    # across them is the intent, not a choice being overwritten.
    execute(~s|UPDATE rooms SET "hold_injection?" = true WHERE "hold_injection?" = false|)
  end

  def down do
    alter table(:rooms) do
      modify :hold_injection?, :boolean, default: false
    end
  end
end
