defmodule Quorum.Repo.Migrations.AddQuestionAiFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:questions) do
      add :held_reason, :text
      add :pointer_reading_ids, {:array, :uuid}, null: false, default: []
      add :answer_draft, :text
    end

    alter table(:rooms) do
      add :hold_injection?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:rooms) do
      remove :hold_injection?
    end

    alter table(:questions) do
      remove :answer_draft
      remove :pointer_reading_ids
      remove :held_reason
    end
  end
end
