defmodule Quorum.Repo.Migrations.AddSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:readings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :detail, :text
      add :url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id,
          references(:rooms,
            column: :id,
            name: "readings_room_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:rooms) do
      add :projection_light_from, :text, null: false, default: "#E9E9E9"
      add :projection_light_to, :text, null: false, default: "#FAFAFA"
      add :projection_dark_from, :text, null: false, default: "#1A1A1A"
      add :projection_dark_to, :text, null: false, default: "#313131"
      add :projection_angle, :bigint, null: false, default: 60
      add :projection_drift?, :boolean, null: false, default: true
      add :readings_pointer?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:rooms) do
      remove :readings_pointer?
      remove :projection_drift?
      remove :projection_angle
      remove :projection_dark_to
      remove :projection_dark_from
      remove :projection_light_to
      remove :projection_light_from
    end

    drop constraint(:readings, "readings_room_id_fkey")

    drop table(:readings)
  end
end
