defmodule Quorum.Repo.Migrations.AddDefaultHeldWords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      modify :held_words, {:array, :text}, default: nil
    end
  end

  def down do
    alter table(:rooms) do
      modify :held_words, {:array, :text}, default: []
    end
  end
end
