defmodule Quorum.Repo.Migrations.AddHoldTriggers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      add :hold_links?, :boolean, null: false, default: false
      add :hold_first_question?, :boolean, null: false, default: false
    end

    alter table(:users) do
      add :hold_for_review_default?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :hold_for_review_default?
    end

    alter table(:rooms) do
      remove :hold_first_question?
      remove :hold_links?
    end
  end
end
