defmodule Quorum.Repo.Migrations.AddHallToRoom do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      add :projection_dark?, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:rooms) do
      remove :projection_dark?
    end
  end
end
