defmodule Quorum.Repo.Migrations.AddAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:login_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :used_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid, null: false
    end

    create unique_index(:login_tokens, [:token], name: "login_tokens_unique_token_index")

    alter table(:rooms) do
      add :owner_id, :uuid
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:login_tokens) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "login_tokens_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:rooms) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "rooms_owner_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:users) do
      add :email, :text, null: false
      add :name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :name
      remove :email
    end

    drop constraint(:rooms, "rooms_owner_id_fkey")

    alter table(:rooms) do
      modify :owner_id, :uuid
    end

    drop constraint(:login_tokens, "login_tokens_user_id_fkey")

    alter table(:login_tokens) do
      modify :user_id, :uuid
    end

    drop table(:users)

    alter table(:rooms) do
      remove :owner_id
    end

    drop_if_exists unique_index(:login_tokens, [:token], name: "login_tokens_unique_token_index")

    drop table(:login_tokens)
  end
end
