defmodule Quorum.Repo.Migrations.AddAiCalls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_calls, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :purpose, :text, null: false
      add :room_id, :uuid
      add :owner_id, :uuid
      add :provider, :text
      add :model, :text
      add :input_tokens, :bigint
      add :output_tokens, :bigint
      add :elapsed_ms, :bigint
      add :cost, :decimal
      add :ok?, :boolean, null: false, default: true
      add :error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:ai_calls)
  end
end
