defmodule Quorum.Repo.Migrations.AddDemoFlag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      add :demo?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:rooms) do
      remove :demo?
    end
  end
end
