defmodule Quorum.Repo.Migrations.InitialSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:questions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false
      add :display_name, :text
      add :submitter_token, :text, null: false
      add :status, :text, null: false, default: "visible"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id, :uuid, null: false
    end

    create table(:rooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:questions) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "questions_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:rooms) do
      add :name, :text, null: false
      add :join_code, :text, null: false
      add :host_token, :text, null: false
      add :status, :text, null: false, default: "open"
      add :auto_close_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:rooms, [:host_token], name: "rooms_unique_host_token_index")

    create unique_index(:rooms, [:join_code], name: "rooms_unique_join_code_index")

    create table(:votes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :voter_token, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :question_id,
          references(:questions,
            column: :id,
            name: "votes_question_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:votes, [:question_id, :voter_token], name: "votes_unique_vote_index")
  end

  def down do
    drop constraint(:votes, "votes_question_id_fkey")

    drop_if_exists unique_index(:votes, [:question_id, :voter_token],
                     name: "votes_unique_vote_index"
                   )

    drop table(:votes)

    drop_if_exists unique_index(:rooms, [:join_code], name: "rooms_unique_join_code_index")

    drop_if_exists unique_index(:rooms, [:host_token], name: "rooms_unique_host_token_index")

    alter table(:rooms) do
      remove :updated_at
      remove :inserted_at
      remove :auto_close_at
      remove :status
      remove :host_token
      remove :join_code
      remove :name
    end

    drop constraint(:questions, "questions_room_id_fkey")

    alter table(:questions) do
      modify :room_id, :uuid
    end

    drop table(:rooms)

    drop table(:questions)
  end
end
