defmodule Quorum.Repo.Migrations.CascadeQuestionsWithRoom do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:questions, "questions_room_id_fkey")

    alter table(:questions) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "questions_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:questions, "questions_room_id_fkey")

    alter table(:questions) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "questions_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
